private_key_path: ./inet256_private2.pem

api_addr: 127.0.0.1:25602

networks:
- onehop

transports:
- udp: "0.0.0.0:44445"
  nat_upnp: false

peers:
- id: CdAAo92_R56A90eTwyh_yWkE0ikfI_rIOojZf-e6Hqo
  addrs:
  - noise+udp://CdAAo92_R56A90eTwyh_yWkE0ikfI_rIOojZf-e6Hqo@127.0.0.1:44444
